# -*- coding: utf-8 -*-
"""FinalProject_Anirudh_Rangi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUnsNYIWFylKps8RNH9G13NgyU9v-MEg

## Final Project : A Python Program to Display Calendar


The function takes in month_start, year_start, month_end, year_end and returns
the range of calendar for the following

Example:
```
print_calendar_in_range(11, 2023, 2, 2024)

November 2023
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30

   December 2023
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31

    January 2024
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30 31

   February 2024
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29
```
"""

#importing module
import calendar

def print_calendar_in_range(month_start, year_start, month_end, year_end):
    """
    This function returns the calendar for the range of the parameters provided

    Args: int: month_start, year_start, month_end, year_end

    returns: calendar for the parameters provided
    """
    # Iterate through each month-year combination in the specified range
    for year in range(year_start, year_end + 1):
        if year == year_start:
          start_month = month_start
        else:
          start_month = 1

        if year == year_end:
           end_month = month_end
        else:
           end_month = 12
        for month in range(start_month, end_month + 1):
            print(calendar.month(year, month),'\n')